### PR TITLE
Cc parent optionals fix

### PR DESCRIPTION
**Pull request by jecede**
supports optional fields in parent classes when using the copy constructors and optional getters.

assigns a property with this.prop1 = other.getProp1().orElse(null) instead of the optional returned by the getter.

### CODE REVIEW

**Comment by sabomichal** [comment]
It doesn't compile. I will try to fix it.

**Comment by sabomichal** [comment]
The tests seems not correct, the one you modified wasn't using the getter method (no inheritance and it actually compiles ok (you have to use maven profile selftest)), so I have change it, however it is still not correct when some other options are turned on. I have pushed a branch with your fix and my modifications in this repo.

**Comment by jecede** [comment]
I hadn't noticed the selftest profile. Updated my change to make your tests succeed, but I do not have the oversight to see if the current testcases cover everything.

**Comment by sabomichal** [comment]
closes #142

**Pull request merged**
