### PR TITLE
Add an option to leave collections mutable

### PR DESCRIPTION
**Pull request by janblok**
We have a usecase where we need the collection mutable but the objects not.
So introduced an option for this behaviour

Also changed the constructor to protected scope if there are more that 8 parameters and builder is present

### CODE REVIEW

**Comment by sabomichal** [comment]
Could you please provide a new PR with following changes:
- leave the snapshot version as is, it is a convention I (we) do use
- do not alter the constructor behavior when there is more than 8 args. If it is really necessary, an option where you can provide the number of args would be better.

**Comment by janblok** [comment]
Reverted the snapshot version as requested.
The public constructor arg limit is an option/setting as well now, by default its the same as before.
Renamed the leavecollection option to skipcollections, which is a better name for the option

**Comment by sabomichal** [comment]
squash merged

**Comment by sabomichal** [comment]
I really do not know how to mark this merged since it was squashed.

**Comment by janblok** [comment]
Any plans for a new  release?

**Comment by sabomichal** [comment]
yes, soon.

**Pull request closed without merging**
