### PR TITLE
Work on xjc output

### PR DESCRIPTION
**Pull request by janblok**
The plugin did modify generated code based on model from xsd. 
When more xjc plugins are used this is incorrect behaviour, the adaptations should work from the code model and not the origional xsd model.

This pull request makes it possible to combine the immutable-xjc plugin with many other xjc plugins, for example my configuration contains many extensions:
<arg>-extension</arg>
<arg>-Xnamespace-prefix</arg>
<arg>-Xjavadoc</arg>
<arg>-Xxew</arg>
<arg>-Xxew:instantiate lazy</arg>
<arg>-Xxew:collection java.util.LinkedHashSet</arg>
<arg>-Xxew:collectionInterface java.util.Set</arg>
<arg>-xmladapter</arg>
<arg>-immutable</arg>
<arg>-imm-builder</arg>
<arg>-imm-inheritbuilder</arg>
<arg>-imm-cc</arg>
<arg>-imm-constructordefaults</arg>
<arg>-imm-skipcollections</arg>
<arg>-imm-pubconstructormaxargs=8</arg>
<arg>-Xbg</arg>

And it still works :-)

### CODE REVIEW

**Comment by janblok** [comment]
Not sure why more than last 3 commits are showing, since those where part of prev pull req.

**Comment by sabomichal** [comment]
did you try to run the tests?

**Comment by janblok** [comment]
hmm, I was under the impression the test are always ran with maven, but they are disabled by default in this pom it seems.

mvn install -Pselftest 
is the way to run the tests? (perhaps something for the readme?)

**Comment by sabomichal** [comment]
correct, this was the simplest way to do the testing, a selftest. First run mvn install to have the current version of the plugin in the local repository and then run mvn install -Pselftest.

**Comment by janblok** [comment]
will make a new pull req asap :-)

**Comment by sabomichal** [comment]
Furthermore, why did you change the compiler plugin settings in the pom? Since java 9, you can specify this new property. Take a look for example here - https://www.baeldung.com/maven-java-version.

**Pull request merged**
